#!/bin/bash

make clean
clear
make
echo -e "\n Enter the mod to run: '--normal', '--test' or '--dock'"
read mod
if [ $mod = '--dock' ]
then
doxygen documentation/Doxyfile
open documentation/html/index.html
else
./ss $mod
fi
